---
version: '3'
services:
  frontend:
    image: frontend-image
    ports:
      - "8085:80"
    networks:
      - frontend-network
      - backend-network
  
  backend:
    image: venkynagidi/image1:latest
    ports:
      - "3000:3000"
    networks:
      - backend-network
      - frontend-network
      
networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge

